#
# Copyright (c) 2025 - present - Yupiik SAS - https://www.yupiik.com
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

services:

  # Monitor Elasticsearch
  metrics-elasticsearch-01:
    container_name: metrics-elasticsearch-01
    image: elasticsearch:8.17.3
    ports:
      - "9200:9200"
    environment:
      - node.name="metrics-elasticsearch-01"
      - cluster.name="metrics-elasticsearch"
      - cluster.initial_master_nodes=metrics-elasticsearch-01,metrics-elasticsearch-02,metrics-elasticsearch-03
      - network.host=0.0.0.0
      - discovery.seed_hosts=metrics-elasticsearch-02,metrics-elasticsearch-03
      - http.max_content_length=500mb
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - ES_JAVA_OPTS=-Xms750m -Xmx750m
    healthcheck:
      test: curl -s http://metrics-elasticsearch-01:9200 >/dev/null || exit 1
      interval: 10s
      timeout: 10s
      retries: 120

  metrics-elasticsearch-02:
    container_name: metrics-elasticsearch-02
    image: elasticsearch:8.17.3
    ports:
      - "9201:9200"
    environment:
      - node.name="metrics-elasticsearch-02"
      - cluster.name="metrics-elasticsearch"
      - cluster.initial_master_nodes=metrics-elasticsearch-01,metrics-elasticsearch-02,metrics-elasticsearch-03
      - network.host=0.0.0.0
      - discovery.seed_hosts=metrics-elasticsearch-01,metrics-elasticsearch-03
      - http.max_content_length=500mb
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - ES_JAVA_OPTS=-Xms750m -Xmx750m
    healthcheck:
      test: curl -s http://metrics-elasticsearch-02:9200 >/dev/null || exit 1
      interval: 10s
      timeout: 10s
      retries: 120

  metrics-elasticsearch-03:
    container_name: metrics-elasticsearch-03
    image: elasticsearch:8.17.3
    ports:
      - "9202:9200"
    environment:
      - node.name="metrics-elasticsearch-03"
      - cluster.name="metrics-elasticsearch"
      - cluster.initial_master_nodes=metrics-elasticsearch-01,metrics-elasticsearch-02,metrics-elasticsearch-03
      - network.host=0.0.0.0
      - discovery.seed_hosts=metrics-elasticsearch-02,metrics-elasticsearch-01
      - http.max_content_length=500mb
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - ES_JAVA_OPTS=-Xms750m -Xmx750m
    healthcheck:
      test: curl -s http://metrics-elasticsearch-03:9200 >/dev/null || exit 1
      interval: 10s
      timeout: 10s
      retries: 120

  # Kibana
  metrics-kibana:
    depends_on:
      metrics-elasticsearch-01:
        condition: service_healthy
      metrics-elasticsearch-02:
        condition: service_healthy
      metrics-elasticsearch-03:
        condition: service_healthy
    container_name: metrics-kibana
    image: kibana:8.17.3
    volumes:
      - ./config/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    ports:
      - "5601:5601"
    restart: on-failure

  #Mock metrics endpoint
  metrics-mock:
    image: mockserver/mockserver:5.14.0
    ports:
      - "1080:1080"
    environment:
      MOCKSERVER_PROPERTY_FILE: /config/mockserver.properties
      MOCKSERVER_INITIALIZATION_JSON_PATH: /config/expectationInitialiser.json
      MOCKSERVER_LOG_LEVEL: WARN
    volumes:
      - ./config/mock:/config

  # Metrics scraper
  metricsScraper:
    depends_on:
      metrics-elasticsearch-01:
        condition: service_healthy
      metrics-elasticsearch-02:
        condition: service_healthy
      metrics-elasticsearch-03:
        condition: service_healthy
    image: ossyupiik/metrics-scraper:1.0.6-SNAPSHOT
    env_file:
      - ./config/metricsScraper/setup.env
    ports:
      - "5005:5005"