services:

  # Monitor Elasticsearch
  metrics-elasticsearch:
    container_name: metrics-elasticsearch
    image: elasticsearch:7.4.0
    volumes:
      - ./config/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - 9200:9200
    environment:
      discovery.type: single-node

  # Kibana
  metrics-kibana:
    container_name: metrics-kibana
    image: kibana:7.4.0
    volumes:
      - ./config/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    ports:
      - 5601:5601
    restart: on-failure

  #Mock metrics endpoint
  metrics-mock:
    image: mockserver/mockserver:5.14.0
    ports:
      - 1080:1080
    environment:
      MOCKSERVER_PROPERTY_FILE: /config/mockserver.properties
      MOCKSERVER_INITIALIZATION_JSON_PATH: /config/expectationInitialiser.json
    volumes:
      - ./config/mock:/config

  # Metrics scrapper
  metricsScrapper:
    image: metrics-scrapper/metrics-scrapper:1.0.0-SNAPSHOT
    env_file:
      - ./config/metricsScrapper/setup.env
    depends_on:
      - metrics-mock
      - metrics-elasticsearch
      - metrics-kibana